app:
  build: .
  links:
   - db
  ports:
   - "3000:3000" # change to whatever port is to be used
  environment:
   - NODE_ENV=development # production for staging
  volumes:
    - .:/usr/src/app/
    - /usr/src/app/node_modules
  #env_file:
  # - ./server/config/development.env # required only if you have environment settings to load
db:
  image: mongo
  ports:
   - "27017:27017"